### ISSUE TITLE
configuration row attributes not restored

### ISSUE THREAD

**Issue by Halama** [keboola/php-kbc-project-restore#13]
It looks like these [configuration row](https://keboola.docs.apiary.io/#reference/component-configurations/get-configuration-row-detail/row-detail) attributes are not restored:
- name
- description
- isDisabled

https://github.com/keboola/php-kbc-project-restore/blob/e899c4fdd4601baf6b469fc36ab715180ec339ac/src/S3Restore.php#L526

**Comment by Halama** [comment]
po fixu bude potřeba updatnout a releasnout https://github.com/keboola/app-project-restore appku která tuto knihovnu využívá.

**Comment by ErikZigo** [comment]
Jeste jsem si vsiml ze se nerestoruje `rowSortOrder` u konfigurace
