### ISSUE TITLE
List configurations in backup

### ISSUE THREAD

**Issue by ErikZigo** [keboola/php-kbc-project-restore#6]
Create methods allowing load informations about KBC configurations in backup.

**Comment by Halama** [comment]
Pro ten restore gd writeru to nakonec nejspíš nebude potřeba https://github.com/keboola/connection/issues/1341#issuecomment-389449149

**Comment by ErikZigo** [comment]
Aha sakra, tak to jsem to delal zbytecne :-) Jo ta appka ze se to spusti v zdrojovem projektu je asi lepsi.

**Comment by ErikZigo** [comment]
Zaviram, tahle uprava nakonec nebude potreba
